#pragma once

#define CX_FONT_REGULAR     0
#define CX_FONT_BOLD        3

#define CX_FONT_SIZE_SMALL  0
#define CX_FONT_SIZE_NORMAL 1
#define CX_FONT_SIZE_LARGE  2

#define CX_COLOR_PRIMARY { CX_RGBA_FROM_HEX(0xFF0277BD) }
#define CX_COLOR_PRIMARY_HOVERED { CX_RGBA_FROM_HEX(0xB00277BD) }
#define CX_COLOR_PRIMARY_ACTIVE { CX_RGBA_FROM_HEX(0x600277BD) }
