#include "serialization/DefaultSerializers.h"

namespace Calyx {

    CX_DEFAULT_TYPE_SERIALIZER_IMPL(vec2);
    CX_DEFAULT_TYPE_SERIALIZER_IMPL(vec3);
    CX_DEFAULT_TYPE_SERIALIZER_IMPL(vec4);

    CX_DEFAULT_TYPE_SERIALIZER_IMPL(mat2);
    CX_DEFAULT_TYPE_SERIALIZER_IMPL(mat3);
    CX_DEFAULT_TYPE_SERIALIZER_IMPL(mat4);

}