#pragma once

#define CX_ON_INSPECTOR_GUI OnInspectorGUI
#define CX_ON_INSPECTOR_GUI_HS CX_CONCAT(CX_XSTR(CX_ON_INSPECTOR_GUI),_hs)

#define CX_ON_INSPECTOR_CONTEXT_GUI OnInspectorContextGUI
#define CX_ON_INSPECTOR_CONTEXT_GUI_HS CX_CONCAT(CX_XSTR(CX_ON_INSPECTOR_CONTEXT_GUI),_hs)